version: 2.1

orbs:
  docker: banzaicloud/docker@0.0.5

workflows:
  version: 2
  ci:
    jobs:
      - docker/build:
          name: Controller docker build
          executor: docker/machine-dlc
          image: banzaicloud/cert-manager-controller
          tag: ${CIRCLE_BRANCH//\//_}
          dockerfile: build/docker/Dockerfile.controller
          filters:
            branches:
              only: /^.+-fips$/
            tags:
              ignore: /.*/
      - docker/build:
          name: CAInjector docker build
          executor: docker/machine-dlc
          image: banzaicloud/cert-manager-cainjector
          tag: ${CIRCLE_BRANCH//\//_}
          dockerfile: build/docker/Dockerfile.cainjector
          filters:
            branches:
              only: /^.+-fips$/
            tags:
              ignore: /.*/
      - docker/build:
          name: ACMESolver docker build
          executor: docker/machine-dlc
          image: banzaicloud/cert-manager-acmesolver
          tag: ${CIRCLE_BRANCH//\//_}
          dockerfile: build/docker/Dockerfile.acmesolver
          filters:
            branches:
              only: /^.+-fips$/
            tags:
              ignore: /.*/
      - docker/build:
          name: Webhook docker build
          executor: docker/machine-dlc
          image: banzaicloud/cert-manager-webhook
          tag: ${CIRCLE_BRANCH//\//_}
          dockerfile: build/docker/Dockerfile.webhook
          filters:
            branches:
              only: /^.+-fips$/
            tags:
              ignore: /.*/

      - docker/custom-publish:
          name: Controller docker build & push
          executor: docker/machine-dlc
          context: image-registries
          login:
            - docker/login
            - docker/ghcr-login
          dockerfile: build/docker/Dockerfile.controller
          push:
            - docker/push:
                registry: docker.io
                image: banzaicloud/cert-manager-controller
                tag: ${CIRCLE_TAG//\//_}
            - docker/push:
                registry: ghcr.io
                image: banzaicloud/cert-manager-controller
                tag: ${CIRCLE_TAG//\//_}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.+-fips$/
      - docker/custom-publish:
          name: CAInjector docker build & push
          executor: docker/machine-dlc
          context: image-registries
          login:
            - docker/login
            - docker/ghcr-login
          dockerfile: build/docker/Dockerfile.cainjector
          push:
            - docker/push:
                registry: docker.io
                image: banzaicloud/cert-manager-cainjector
                tag: ${CIRCLE_TAG//\//_}
            - docker/push:
                registry: ghcr.io
                image: banzaicloud/cert-manager-cainjector
                tag: ${CIRCLE_TAG//\//_}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.+-fips$/
      - docker/custom-publish:
          name: ACMESolver docker build & push
          executor: docker/machine-dlc
          context: image-registries
          login:
            - docker/login
            - docker/ghcr-login
          dockerfile: build/docker/Dockerfile.acmesolver
          push:
            - docker/push:
                registry: docker.io
                image: banzaicloud/cert-manager-acmesolver
                tag: ${CIRCLE_TAG//\//_}
            - docker/push:
                registry: ghcr.io
                image: banzaicloud/cert-manager-acmesolver
                tag: ${CIRCLE_TAG//\//_}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.+-fips$/
      - docker/custom-publish:
          name: Webhook docker build & push
          executor: docker/machine-dlc
          context: image-registries
          login:
            - docker/login
            - docker/ghcr-login
          dockerfile: build/docker/Dockerfile.webhook
          push:
            - docker/push:
                registry: docker.io
                image: banzaicloud/cert-manager-webhook
                tag: ${CIRCLE_TAG//\//_}
            - docker/push:
                registry: ghcr.io
                image: banzaicloud/cert-manager-webhook
                tag: ${CIRCLE_TAG//\//_}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.+-fips$/
