apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingress
spec:
  selector:
    app: ingress
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
        - '*'
      port:
        name: https-443
        number: 443
        protocol: HTTPS
      tls:
        credentialName: ingress-cert
        mode: SIMPLE
        privateKey: sds
        serverCertificate: sds
